n = input('Digite algo: ')
print(type(n))
print(n.isspace())
print(n.isprintable())
print(n.islower())
print(n.isupper())
print(n.isdigit())
print(n.isdecimal())
print(n.isalpha())
print(n.istitle())
print(n.isalnum())
print(n.isidentifier())
